### PR TITLE
Add rel="noopener noreferrer" to target="_blank"

### PR DESCRIPTION
**Pull request by IanDelMar**
Added to class Walker_Nav_Menu in WP 5.2

Fixes issue #425

### CODE REVIEW

**Comment by pattonwebz** [comment]
Did core recently add this as well to the walker and is the method in this PR the same method that they used?

Also should we enforce these values in as well when users have a custom 'rel' defined?

**Comment by IanDelMar** [comment]
It is the same method: [https://core.trac.wordpress.org/changeset/45141/](https://core.trac.wordpress.org/changeset/45141/).

I read about concerns that some affiliate links won't monetize if rel="noopener noreferrer" is set. I don't know whether that is actually the case and was not interested enough to dig deeper. However, not adding rel="noopener noreferrer" when a custom rel is defined, would give users who would like to add affiliate links to their menu and are concerned about them not working the option to prevent the rel="noopener noreferrer".

**Review by pattonwebz — APPROVED** [review]
LGTM will merge soon :)

**Comment by IanDelMar** [comment]
@pattonwebz closes #425.

**Pull request merged**
