### PR TITLE
Mention Performance in the README

### PR DESCRIPTION
**Pull request by szepeviktor**
With a link to Tiny navigation menu cache

### CODE REVIEW

**Comment by pattonwebz** [comment]
If we were to add some info about caching menus to the readme it would need to have some info within the readme as well as the link to the example.

For me as well it would need to have the benefits measured and demonstrated as - based on my own use of caching menus - I am skeptical there are any true benefits to it.

I have used transients for caching navs on several fairly high traffic sites for a few years now and we seen the benefits diminish quickly for 2 reasons.

First is because processed html for the menu is not globally cacheable - to be truly globally cachable it needs to be the same markup for every request, because sometimes the .active class is moved depending on the page viewed nav menus are rarely global objects. You get much better cache hits and a smaller overall cache size (due to less unique menu objects) when you cache the root query and process the items on each request.

The 2nd reason that caching is not very valuable for menus is because the menu items are created with a query that, once executed, is stored in the query cache. The time to lookup the menu in the query cache vs time to look it up the transient is basically the same.

**Comment by szepeviktor** [comment]
OK.
I'll provide you some measurements for you, and some very simple instructions to repeat my measurement.

**Comment by szepeviktor** [comment]
I am not halfway there but it is huge!
A site with Redis object cache generates its only one menu in **0.015 seconds**
`view-source:https://www.atlantischild.hu/trening/tr%c3%a9ningszervez%c3%a9s/`
WordPress' run time is ~200 milisec thus it is 7.5%

**Comment by szepeviktor** [comment]
With caching it is **0.00013** shorter than 1 milisec.

```php
$nav_start = microtime( true );
wp_nav_menu( ... );
echo '<!-- Time: ' . ( microtime( true ) - $nav_start ) . ' -->';
```

My opinion is that a fast site gathers it speed from these tiny improvements.

**Comment by pattonwebz** [comment]
I can't disagree with you about many small improvements is what makes a fast site. Totally with you there :)

Those figures do look awesome and numbers like that are exactly why we decided to implement caching for menus on those sites. However it turns out that those numbers we saw initially were misleading. I'll explain why but first I should say that I am fully capable of being proved wrong here and if I am wrong I encourage you to prove me so lol

So the reasons why I think those numbers are misleading is because firstly menus on most sites are neither tiny pieces of data nor globally cacheable. On a site with a simple menu that doesn't matter but on a site with a larger menu (say 20 items total) all of those unique permutations of where `.active` is etc need cached. Since markup for a 20 item menu with dropdowns is a not tiny piece of data (I just tested a menu with maybe 15 items, it was 5kb) the overall size of cache goes up a bunch (a larger cache often results in longer lookups - although not always) as well more unique permutations resulting in more cache misses.

I tried to cache menus in production on high traffic, single node, sites (think WP Engine dedicated server running at near capacity) and things like resource contention come into play. On very small sites the benefits might be fairly steady but we saw very quickly diminishing benefits on medium sites and on large sites it only took a minute after cache was flushed for the benefits to be barely noticeable.

EDIT: When I say 'small', 'medium', 'large' I mean in terms of traffic, not in terms of the database size.

I think that if you were to test cached vs not-cached on a site with 20 items in the menu and track timings for 1000 hits in 60 seconds spread randomly between all of the 20 pages so you could which would trigger all the unique permutations of the menu then you would find that the timings would be very similar. They would be so similar because of the menu already residing in the query cache and, providing that is also stored in some kind of persistent object cache like redis or memcached, that's almost the same as it being stored there using the transients API.

But like I said I'm very open to being incorrect here and I'm actually certain there would be benefits for low traffic sites if fairly long cache lifetimes are set. On larger sites I think benefits are fairly small if any.

**Comment by szepeviktor** [comment]
AFAIK my measurements are query cache vs. nav menu HTML output caching.

The only thing I can offer you is optimizing one of your medium or high load server as I do managed hosting only - as you may noticed.

https://github.com/szepeviktor

**Comment by szepeviktor** [comment]
ps. 20 pages × 10 kB HTML is 200 kB (Redis) memory usage on a multi-GB server.

**Comment by szepeviktor** [comment]
"1000 hits in 60 seconds" means after a couple of minutes your benefit is 15 msec × 1000 per minute which equals 15 seconds per minute.

**Comment by pattonwebz** [comment]
For sure I was playing devils advocate here and picking out some unlikely scenarios. I didn't know you did managed hosting however I saw some of your repos and was aware that you understood performance aspects and tracking (part of the reason I was so pushy with findings from a previously failed long term test of mine). I also figured just to prove me wrong you might actually test and be able to give me the numbers of 1000 hits in 60 seconds lol

I'm not above saying when I'm wrong. I, very happily, concede that my findings were not matching with what the majority of other users see :smile:. I was wrong :stuck_out_tongue: 

Reopening as I now feel this is worth including (but I do still want to include some figures so.... since your a managed hosting expert care to donate some time and test data? lol)

**Comment by pattonwebz** [comment]
Hey @szepeviktor, 

I'm going to close out this PR for now in the interests of starting the latest update with a clean slate on the PRs. If you wanted to update his to fix the conflicts and merge this text about performance into the notes added about caching I'll look to merge that. Or don't update it if you haven't got the time, no pressure lol

**Pull request closed without merging**
