### PR TITLE
add .nav-item.dropdown show to sub-menus

### PR DESCRIPTION
**Pull request by 4thguy**
add .nav-item.dropdown show to sub-menus to make it work with bootstrap as expected

### CODE REVIEW

**Comment by pattonwebz** [comment]
This sounds like a Bootstrap v4 markup for menus. Are you using one of the BS4 alphas?

Bootstrap 4 support is planned and will be released when Bootstrap 4 is closer to official release.

If you are working with BS4 and need the walker to work then I prepared a really early version that works with v4 at this branch https://github.com/wp-bootstrap/wp-bootstrap-navwalker/tree/v4

**Comment by 4thguy** [comment]
Hi pattonwebs,

I really hate to be *that* guy, but the PR is clearly for the `v4` branch. I admit that the description could have been worded better though.

```4thguy  wants to merge 1 commit into wp-bootstrap:v4 from 4thguy:patch-1```

Unless I missed something, the `v4` branch as it was when I first submitted the PR did not work as intended.

**Comment by pattonwebz** [comment]
No need to apologize for being 'that guy'. You were right to call me on this as I totally missed the intent.

I must have overlooked the branch this is for and misunderstood. Clearly it's BS4 markup because it's for BS4. If i had checked the branch the description weeks have made perfect sense to me.

Reopening now, will see about merging this in sometime in the near future.

Thank you for contributing!

**Comment by 4thguy** [comment]
:+1:

**Comment by pattonwebz** [comment]
Dropdowns are working with the latest version of the walker. Closing as already fixed but thank you for the PR :smile:

**Pull request closed without merging**
