### PR TITLE
"active"-class for "current-menu-parent"

### PR DESCRIPTION
**Pull request by zyberspace**
With this the dropdown is showed active when one of his childs is active.

### CODE REVIEW

**Comment by pupadupa** [comment]
maybe for child pages if parent page in menu it should be active two:

```
if ( in_array( 'current-menu-item', $classes ) || in_array( 'current-menu-parent', $classes ) || in_array( 'current-page-ancestor', $classes ))
```

**Comment by marcelo2605** [comment]
Is possible to include third level menu?

**Comment by marcelo2605** [comment]
Found: 

`if ( in_array( 'current-menu-item', $classes ) || in_array( 'current-menu-parent', $classes ) || in_array( 'current_page_ancestor', $classes ) )`

**Comment by LouisMilotte** [comment]
@marcelo2605 Not to be rude, but this question is asked dozens of times in a given week. Please use the repositories search functionality to find replies.

The last update I saw from bootstrap is that third-level menus are not possible (V3).

**Comment by marcelo2605** [comment]
@LouisMilotte No problem. You're right. I should have looked better. But if you make some changes, you can add third-level menus using V3.

**Comment by pattonwebz** [comment]
I think we could rebase this and merge it in if we don't already do this.

**Comment by zyberspace** [comment]
As this is in #286 now, i guess i can finally close this PR? @pattonwebz

**Pull request closed without merging**
