### PR TITLE
Implement correct WP plugin meta

### PR DESCRIPTION
**Pull request by szepeviktor**
See https://codex.wordpress.org/File_Header#Plugin_File_Header_Example

### CODE REVIEW

**Review by pattonwebz — APPROVED** [review]

**Comment by szepeviktor** [comment]
@pattonwebz I thought overarching `if`-s demand an `endif`.

**Comment by pattonwebz** [comment]
@szepeviktor you are correct that the coding styles tend to call for use of `if() :`...`endif;` however on a personal level I prefer consistency of braces everywhere :)

What's your personal thoughts?

**Comment by szepeviktor** [comment]
> What's your personal thoughts?

Thank you for asking.
While working I strive to 100% avoid my person.

**Comment by pattonwebz** [comment]
> > What's your personal thoughts?
> 
> Thank you for asking.
> While working I strive to 100% avoid my person.

Is this work for you? For me this is an open source sideproject and not strictly work. I am able to allow some person preference slip into the code on this one. Are you telling me that for work reasons you would rather this fully followed the wp code styles and that you would rather have it as a `if...endif;`?

**Comment by szepeviktor** [comment]
> Is this work for you?

My clear aim with GitHub contributions is to be hired and work for long years with my new partner/s.

**Comment by pattonwebz** [comment]
> My clear aim with GitHub contributions is to have hired and work for long years.

Understood, I wish you good fortunes with that :+1:

**Pull request merged**
