### PR TITLE
Added support for multi-level dropdowns

### PR DESCRIPTION
**Pull request by Jmz**
Added support for more levels of drop down menus.

### CODE REVIEW

**Comment by SideQuestDIY** [comment]
Hey @Jmz,

Thanks for checking out the class and contributing, its good to know someone found it useful.

That said, I am not going to merge your pull request at this time. The reasons are two fold. 
- I agree with @mdo's decision not to implement multi-level menus in Bootstrap (https://github.com/twitter/bootstrap/issues/424) with the rise of mobile/touch browsers multi-level menus have become unusable in many circumstances.
- This class is intended to help theme designers format default WordPress menus to use the native Bootstrap CSS & JS without making changes/additions to the Bootstrap library itself. Because implementing multi-level menus would require additional CSS to implement, this changes the intention of the class.

**Comment by SideQuestDIY** [comment]
Sorry Man,

I guess I didn't dig to deep on the last release, it seems they have added multi-level dropdowns. I will be implementing your code with a slight modification in my second update today. Thanks for the input and I will make sure to give you credit :)

**Comment by pattonwebz** [comment]
Hey @twittem, did you ever nail down the multi-level menus in the walker like you planned?

**Comment by ghost** [comment]
@pattonwebz Google does not recommend you have more than ONE drop down level for your menu. Its bad for seo.

**Comment by pattonwebz** [comment]
@brody, I'm aware of several reasons why multi levels of dropdown are not recommended. None of them have anything to do with Google's stance on them and their negative SEO value. Can you send me a link to your reference for that?

I'd imagine any negative SEO value wouldn't be down to the fact that there are multiple levels of menu - rather it's likely that it's to do with the sheer amount of links/markup vs the amount of user facing content.

**Comment by ghost** [comment]
@pattonwebz its not just Google, when you use multiple drop down levels you are hindering website usability. I am assuming you are not a pro web designer

**Comment by SideQuestDIY** [comment]
@pattonwebz I have no plans to support multiple levels in the core walker as it is not
natively supported by Bootstrap 3.x

**Comment by pattonwebz** [comment]
@brody182 lol feel free to assume whatever you want to, I don't want to argue about what makes someone a 'pro web designer' and what doesn't. I didn't find anything in Google's guidelines that suggests multiple levels of dropdown are a negative SEO factor so I still stand firm that you're misrepresenting the true purpose (if there is one) of whatever you read that states it is a negative factor.

And as an FYI SEO is not a issue in the project as it's an entirely private infrastructure with no world facing, or other external, features.

@twittem yeah that's what I figured but noticed that you stated on this thread that you would be integrating the multi-level dropdowns. Should have looked at what version of the walker this thread was referencing (IE 2.x not 3.x), 

I'll just continue modifying the walker and adding my own CSS for the additional dropdowns as always :)

Also while your around I commented the other day on the other repo you added us to (the strapping-WP one) asking if anyone there is still interested in pursuing the ad-free open source format that was spoke of there. Nobody replied, I'm guessing that you guys are either too busy at the moment or you stopped following the thread - so not sure you even seen my comment :(

**Pull request closed without merging**
