### PR TITLE
Check if Walker_Nav_Menu class exists

### PR DESCRIPTION
**Pull request by hitankar**
Fixes #

#### Changes proposed in this Pull Request:

* checking if Walker_Nav_Menu exists to avoid errors when using with composer

#### Testing instructions:

*

### CODE REVIEW

**Comment by pattonwebz** [comment]
I'm uncertain how this would help with composer installs. Wouldn't this just patch over a different issue that causes the `Walker_Nav_Menu` class to not exist yet? By all points when a theme is included that class should already exist.

**Review by bhubbard — APPROVED** [review]

**Comment by bhubbard** [comment]
@pattonwebz I think it should be an ok check, ideally this should never happen with a standard theme/wp setup. Maybe we should add a `else` to the if statements and provide a WP Error?

**Comment by pattonwebz** [comment]
Hey @bhubbard good to see you around :)

After looking at this again now I do agree this is an ok/safe check to perform here and adding it causes no negatives. Don't think we need the extra WP_Error returned on failure because a failure would likely mean that something else more serious is wrong elsewhere.

**Review by pattonwebz — APPROVED** [review]

**Comment by pattonwebz** [comment]
Also checking travis fails they are minor things so this could be merged still and I would make a PR later that resolved any PHPCS warnings.

**Pull request closed without merging**
