### PR TITLE
Updated class to use WP filters instead. 

### PR DESCRIPTION
**Pull request by ghost**
Summary of changes and original pull request history [here](https://github.com/twittem/wp-bootstrap-navwalker/pull/129).
## tl;dr

It is more robust to rely on Wordpress' filter/hook framework than to subclass Walker_Nav_Menu. This avoids code duplication and arguably increases readability. Updated class is used and behaves exactly like the original class.

### CODE REVIEW

**Comment by dahlskebank** [comment]
Thanks! :+1:

**Comment by ghost** [comment]
@dahlskebank What do you mean? Do you have any plans to merge/review?

**Comment by dahlskebank** [comment]
@bucaran Sorry no... not too familiar with how github works, just wanted to thank you for your code! :) I have no idea how to merge or review.

**Comment by ghost** [comment]
@dahlskebank :smile: [I thank you back](http://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1).

**Comment by bucaran** [comment]
This is project is dead.

**Pull request closed without merging**
