### PR TITLE
Fix schema markup

### LINKED ISSUE #440: SiteNavigationElement producing incorrect URLs for schema markup
#### Steps to reproduce the issue:

Run a test on any nav using the wp-bootstrap/wp-bootstrap-navwalker 

Google Schema Testing Tool: https://search.google.com/structured-data/testing-tool

#### What I expected:

Correct URLs to be shown

#### What happened instead:

Incorrect URL is shown in schema markup. Eg. https://www.example.com/menu-item-2787

The menu Id is used as the URL path.

### PR DESCRIPTION
**Pull request by IanDelMar**
Adds itemprop="url" to <a> tag

Fixes #440
Alternative to #441

### CODE REVIEW

**Comment by pattonwebz** [comment]
@IanDelMar hello! Thanks for making all these PRs and working towards fixing a lot of outstanding things. I do not currently have an awful lot of available time to me as I am tied up with the Twenty Twenty theme but I don't want you to think that your help here is not being noticed or valued.

@bhubbard I know Ian from a different project where they use this navwalker and I trust that he knows a lot of this code about as well as you and I do. I really do not know when I will have time to look at merging these so if you did happen to get a little time eyes on these PRs would be great.

**Review by pattonwebz — APPROVED** [review]

**Comment by IanDelMar** [comment]
@pattonwebz, no worries!

**Comment by pattonwebz** [comment]
@IanDelMar as part of a different PR I merged the schema is now removed from the walker entirely. I don't think this PR is necessary anymore unless you believe we should bring back the schema on the items? I was never fully aware of how to implement it or the correct method so removal is likely better than a bad impliemntation, do you agree?

**Comment by IanDelMar** [comment]
@pattonwebz I agree. Are you sure it was removed? It seems as code for adding schema is still there. It's just disabled by default and must be added via the nav menu arguments.

**Comment by pattonwebz** [comment]
I can't remember right now what I was referring to but it does seem like I was mistaken with the previous comment. So you think that the schema should just be removed? My general feeling is that probably is best to be removed completely

**Comment by IanDelMar** [comment]
@pattonwebz Using e.g. `'items_wrap' => '<ul id="%1$s" itemscope class="%2$s">%3$s</ul>'` in the nav menu args adds correct schema markup to the nav menu. If it works and that seems to be the case there's no need to remove it.

**Pull request closed without merging**
