### PR TITLE
Fix Travis builds

### LINKED ISSUE #314: WordPress: Improve Travis config and take advantage of all test features we can
Currently the Travis config fails. Previously it ran on an old base image (precise) which was depreciated in favour of a `trusty` based image. Builds now fail due to various reasons including missing packages for php 5.3 in trusty and probably some more dependencies.

I propose we take a look at the overall Travis config and rework it to fix issues and, if possible, improve it on it by taking advantage of newer features or more in-depth testing.

### PR DESCRIPTION
**Pull request by szepeviktor**
Closes #314

### CODE REVIEW

**Comment by szepeviktor** [comment]
@pattonwebz Please send the $1M!

**Comment by szepeviktor** [comment]
@pattonwebz Could you merge this one?

Sorry for the $1M jokes.

**Comment by pattonwebz** [comment]
@szepeviktor lol don't worry about the $1M jokes - I was just busy the last few days, I wasn't offended. I knew it was a joke... and it's the same kind of joke I might have made in your position lol.

I'll look at this in a few minutes and merge if it's ok :)

**Review by pattonwebz — APPROVED** [review]
Nice, finally got the testing sorted.

Also you made this a lot easier than I had felt like it was when I first looked at it :)

**Comment by pattonwebz** [comment]
Still waiting on the 5.3 multisite test starting and finishing but so far everything green :)

**Comment by szepeviktor** [comment]
> Also you made this a lot easier than I had felt like it was when I first looked at it :)

I've learned from Daniel Bachuber - he taught me on WP-CLI.

**Comment by pattonwebz** [comment]
There's no better source on WP-CLI than the man himself. I should pester him to help me too haha

**Pull request merged**
