### PR TITLE
Add accessibility role attributes to li and a elements

### PR DESCRIPTION
**Pull request by jjs2484**
#### Changes proposed in this Pull Request:

Add li and a menu elements role attributes in accordance with accessibility best practices. See https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html 

#### Testing instructions:

Scan with - https://wave.webaim.org/

### CODE REVIEW

**Comment by IanDelMar** [comment]
AFAIK, that's for application menus not for navigation menus. See https://www.w3.org/WAI/tutorials/menus/flyout/ vs. https://www.w3.org/WAI/tutorials/menus/application-menus/. I guess validation tools are complaining about this because there's a `role="menu"` (which I think shouldn't be there) which requires at least one `role="menuitem"` which is missing.

**Comment by pattonwebz** [comment]
@IanDelMar what makes you think the role shouldn't be on the menu? I am no expert so if you know better I am more than happy to defer a change there to your insights :)

**Comment by mediaformat** [comment]
On the use of roles

> Most HTML has built-in semantics and does not generally need WAI-ARIA. However, when HTML is being used in a non-standard way, like making a button out of a `<div>`, then WAI-ARIA can be added to that `<div>` to make it appear as a button to a screen reader by adding the following: Add the role of “button” (i.e., role="button"), add a null tabindex value (i.e., tabindex="0"), which makes it focusable, then define its state using the aria-pressed attribute, which is updated with JavaScript when the button is pressed. In the case of an actual <button> element, these properties are all already defined, so there is no need to use WAI-ARIA.
https://pressbooks.library.ryerson.ca/wafd/chapter/wai-aria-and-html-5/

So `role="menuitem"`, would only be appropriate where you would be attempting to create menu links from the `<li>` elements themselves, and not having normal links `<a href="index.htm">`

**Comment by IanDelMar** [comment]
@pattonwebz According to the links I provided in my previous comment `role="menu"` is for application menus not for navigation menus.

From https://www.w3.org/WAI/tutorials/menus/application-menus/:
```
<ul role="menubar" id="appmenu">
	…
	<li role="menuitem" aria-haspopup="true">
		Edit
		<ul role="menu">
			<li role="menuitem">Undo</li>
			<li role="menuitem">Redo</li>
			<li role="separator"></li>
			<li role="menuitem">Cut</li>
			<li role="menuitem">Copy</li>
			<li role="menuitem">Paste</li>
			</ul>
		</li>
	…
</ul>
```

From https://www.w3.org/WAI/tutorials/menus/flyout/:
```
<nav aria-label="Main Navigation">
	<ul>
		<li><a href="…">Home</a></li>
		<li><a href="…">Shop</a></li>
		<li class="has-submenu">
			<a href="…" aria-haspopup="true" aria-expanded="false">
				Space Bears
			</a>
			<ul>
				<li><a href="…">Space Bear 6</a></li>
				<li><a href="…">Space Bear 6 Plus</a></li>
			</ul>
		</li>
		<li><a href="…">Mars Cars</a></li>
		<li><a href="…">Contact</a></li>
	</ul>
</nav>
```

Bootstrap follows the [disclosure design pattern](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html) which does not use any menu related aria roles. Also, using `role="menu"` without using 1. `role="menubar"` and 2. `role="menuitem"` makes no sense and gives validation errors as `role="menu"` [requires at least one](https://w3c.github.io/aria/#menu) `role="menuitem"`, `role="menuitemcheckbox"` or `role="menuitemradio"`.

**Comment by pattonwebz** [comment]
Thank you @mediaformat and @IanDelMar for explaining. I agree that removing the items is the better approach. I have already merged that PR.

I am closing this PR as adding these is no longer needed due to removal of the `role="menu"` markup. Thank you for taking the time to make the PR to fix the issues that you found though @jjs2484 , if you have any other suggestions please do open issues or PRs for those and I will look to have them merged.

Thanks again, I am sorry to be closing this PR without merging but I believe the other approach is more suitable.

**Pull request closed without merging**
